export const SET_PERSONLIST = "SET_PERSONLIST";
export const ADD_PERSONLIST = "ADD_PERSONLIST";
export const DELETE_PERSONLIST = "DELETE_PERSONLIST";
export const UPDATE_PERSONLIST = "UPDATE_PERSONLIST";
export const SET_FORMDATA = "SET_FORMDATA";

